# Prod values for the signed-worker
# TODO: fill in when prod is set up

ingress:
  enabled: false

keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 10
  queueLength: "10"

eso:
  enabled: true

env: {}
