# Staging values for the auth service
image:
  repository: 086241318869.dkr.ecr.us-east-1.amazonaws.com/snapdf-auth
  tag: latest

replicas: 1

ingress:
  enabled: true
  path: /auth

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

serviceAccount:
  roleArn: "arn:aws:iam::086241318869:role/snapdf-dev-worker"

env:
  API_URL: "http://k8s-ingressn-ingressn-3f6268c3d3-a2e0602d694b942f.elb.us-east-1.amazonaws.com/api"
  DB_NAME: "snapdf"

eso:
  enabled: true
  secrets:
    - secretKey: JWT_SECRET
      remoteKey: snapdf/jwt-secret
    - secretKey: DB_HOST
      remoteKey: snapdf/db-credentials
      property: host
    - secretKey: DB_USER
      remoteKey: snapdf/db-credentials
      property: username
    - secretKey: DB_PASSWORD
      remoteKey: snapdf/db-credentials
      property: password
