# Dev values for the auth service
image:
  repository: 086241318869.dkr.ecr.us-east-1.amazonaws.com/snapdf-auth
  tag: latest

replicas: 1

ingress:
  enabled: true
  path: /auth

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

env:
  AUTH_USERNAME: "admin"
  API_URL: "http://k8s-ingressn-ingressn-3f6268c3d3-a2e0602d694b942f.elb.us-east-1.amazonaws.com/api"

eso:
  enabled: true
  secrets:
    - secretKey: AUTH_PASSWORD
      remoteKey: snapdf/auth-credentials
    - secretKey: JWT_SECRET
      remoteKey: snapdf/jwt-secret
