{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: {{ .Values.keda.queueURL }}
        queueLength: {{ .Values.keda.queueLength | quote }}
        awsRegion: us-east-1
        identityOwner: operator
{{- end }}
