# Prod values for the signed-worker
image:
  repository: 086241318869.dkr.ecr.us-east-1.amazonaws.com/snapdf-worker
  tag: latest

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

ingress:
  enabled: false

hpa:
  enabled: false

keda:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 10
  queueLength: "10"

eso:
  enabled: true

serviceAccount:
  roleArn: "arn:aws:iam::086241318869:role/snapdf-prod-worker"

env: {}
